server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://rm-m5ee476bu350735gjeo.mysql.rds.aliyuncs.com:3306/cloud_music?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: XuNiit_#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 60000
      connection-timeout: 30000

  redis:
    database: 0
    password:
    port: 6379
    host: localhost
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
#Mybatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-enums-package: com.soft1851.music.admin.entity
  global-config:
    db-config:
      #主键类型:auto主键自增，input用户输入id，id_worker全局唯一的数字id，UUID全局唯一的UUID
      id-type: auto
      #开启驼峰转换
      table-underline: true